### PR TITLE
Fix for OverflowException (Issue System.OverflowException in IFDReader.CreateIDFEntry #36)

### PR DESCRIPTION
**Pull request by codingdave**
Hi, 

this code fragment fixes the overflow exception on my side.

### CODE REVIEW

**Comment by decriptor** [comment]
Awesome, thanks for doing this. Any chance you could add a unit test for this?

**Comment by codingdave** [comment]
Please guide me how you like to have the unit test? I offer using the image I uploaded here but that leads to adding 6MB to the repo for 1 unit test. Do you see any alternative?

**Comment by decriptor** [comment]
That's a good question. There used to be a repository just for binaries, but the place it was hosted killed all repositories, so they are lost. This might be something we need to bring back  :(

Is there any chance that you could shrink the image down a bunch? We really only need the tag information I'd assume?

**Comment by codingdave** [comment]
Here is a 1px image that resembles the problem.
small_small

**Comment by codingdave** [comment]
I've created another one - this time test driven developed and including the jpg

**Comment by codingdave** [comment]
This time test-driven. Hope it works fine for you.

Kind regards,
David

**Comment by decriptor** [comment]
👍

**Pull request merged**
