### PR TITLE
Added support for chapters by implementing the frames CHAP and CTOC

### PR DESCRIPTION
**Pull request by JanRomero**
Hi. This is sort of rudimentary. Ideally I would like to expose the chapters directly from the File’s Tag property and have TagLib handle the internals like generating ids and enforcing uniqueness, but it’s been working fine for me going through `(TagLib.Id3v2.Tag)File.GetTag(TagLib.TagTypes.Id3v2)` and setting the frames up manually.

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/mono/taglib-sharp?pullRequest=228) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/mono/taglib-sharp?pullRequest=228) before we can accept your contribution.<br/><br/>:x: JanRomero [sign now](https://cla.dotnetfoundation.org/mono/taglib-sharp?pullRequest=228)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/mono/taglib-sharp?pullRequest=228) it.</sub>

**Comment by decriptor** [comment]
@JanRomero Thanks! I'm good with the PR. The only ask I have is if you could add unit tests for this?

**Comment by igor-rif-shevchenko** [comment]
@JanRomero @dnfadmin @decriptor Hi guys, will this be merged?

**Comment by igor-rif-shevchenko** [comment]
@decriptor when are you going to push it to nuget?

**Pull request merged**
