### PR TITLE
Implemented support for DSF files

### PR DESCRIPTION
**Pull request by hwahrmann**
This change will implement support for tagging DSF Files as found in DSD container:
http://en.wikipedia.org/wiki/Direct_Stream_Digital

Support has been implemented based on this guide:

http://dsd-guide.com/sites/default/files/white-papers/DSFFileFormatSpec_E.pdf

### CODE REVIEW

**Comment by jezbo7** [comment]
Good work. Excellent addition. Need this merged ASAP.

**Comment by decriptor** [comment]
Any chance you'd be able to add some unit tests for this?

**Comment by hwahrmann** [comment]
in general yes.
Just need to figure out, how to produce a very small DSF file, since they are very big.

BTW, the code itself seems to work, since we are using it in our products MediaPortal and MPTagThat since several months and we were able to Tag DSF files and correctly read them back.

**Comment by hwahrmann** [comment]
Updated the Pull Request with Unit Tests for DSF

**Comment by hwahrmann** [comment]
did not merge with latest master, so my changes to Makefile.am are not reflecting the latest changes. sorry about that

**Comment by lesderid** [comment]
Could you maybe rebase it onto the master and squash your changes into one commit?

**Comment by decriptor** [comment]
It looks like this causes the build to fail. I didn't look very much into it. If you run into any problems just let me know :)

	TagLib/FileTypes.cs(66,18): error CS0234: The type or namespace name `Dsf' does not exist in the namespace `TagLib'. Are you missing an assembly reference?

**Comment by hwahrmann** [comment]
Sorry for the multiple commits. I am not able to run Nunit tests on my windows machine. Always get a "Has no TestFixtures" when run from nunit console.
Will fix that to avoid such stupid mistakes and pushes

**Comment by lesderid** [comment]
You can squash the commits into one by doing `git rebase -i HEAD~5` and changing `pick` on each line to `squash`, except the first one. You'll have to do `git push --force` afterwards to push it to GitHub.

**Comment by hwahrmann** [comment]
Thanks for the suggestion. Tests are failing because of other things, but my changes should be ok

**Pull request merged**
