### PR TITLE
Added support for more RIFF - INFO flags (ISFT, ISMP, ISMF, IDIT)

### PR DESCRIPTION
**Pull request by mlveggo**
Needed more RIFF INFO flags.

ISFT to read/write Software that created the avi
ISMP to read/write Timecode (Smpte) start
ISMF to read/write Timecode frequency (Smpte frequency)
IDIT to read date when media was created

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/mono/taglib-sharp?pullRequest=235) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/mono/taglib-sharp?pullRequest=235) before we can accept your contribution.<br/><br/>:x: mlveggo [sign now](https://cla.dotnetfoundation.org/mono/taglib-sharp?pullRequest=235)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/mono/taglib-sharp?pullRequest=235) it.</sub>

**Comment by decriptor** [comment]
Thanks for the PR. Would you be willing to add some unit tests for your changes?

**Comment by mlveggo** [comment]
I will add unit tests.

**Comment by decriptor** [comment]
@mlveggo Fantastic! Thank you so much!

**Comment by hwahrmann** [comment]
Seems to be ok, after the Unit tests have been added and could be merged

**Comment by benrr101** [comment]
I've got a few concerns with this PR (though I'm not a contributor on the project, so my opinion might not be very valuable):
1) I'm not 100% on the `Software` field being bumped up to the `Tag` class. It seems to be a bit of EXIF that overlapped in RIFF, but I'm not sure if it's a field that's generalized enough across other tagging formats to justify making it part of the Tag base implementation. Though, I have seen "encoded by" or "tagged by" fields in mp3s before. That could be justifiable to make it part of the base `Tag` class.
2) I have the same concerns about the timecode and timecode frequency fields... do any other tagging formats support them? If not, I think it's probably best to not add them to the base `Tag` class. They could definitely still be valuable as a property in the `InfoTag` class.
3) From the spec's I've read, `IDIT` looks to be more of a "date/time the video/image was created" field rather than the date/time of tagging. Are there some forums or such showing `IDIT` being used for tagging date/time? Plus, some ooooollllddd docs from Microsoft seem to show the date format only having one space in between month and day. http://www-mmsp.ece.mcgill.ca/Documents/AudioFormats/WAVE/Docs/RIFFNEW.pdf (pg 6)

**Pull request closed without merging**
