### PR TITLE
Support Latin-1 (or local encodings) in RIFF INFO tag

### PR DESCRIPTION
**Pull request by TsudaKageyu**
Support Latin-1 (or local encodings) in RIFF INFO tag because local encodings are widely used for writing RIFF INFO tag.

### CODE REVIEW

**Comment by rboy1** [comment]
Looks good, essentially it's providing an option for users to set the encoding as Latin-1, still using UTF-8 as the default.

**Comment by rboy1** [comment]
I don't have test scripts but I tested it on this my setup and it's working okay. @decriptor

**Comment by decriptor** [comment]
I don't mind merging this. The code formatting needs to be fixed. ie, tabs instead of spaces. I'll try and fix that and then merge this

**Comment by rboy1** [comment]
@decriptor just checking in on this

**Comment by decriptor** [comment]
Merged from commandline
Commit: 24c938a3f618a5d41a262c9f9ca5abd6aea0b99d

**Pull request closed without merging**
