### PR TITLE
add .Net Core 3.1 target

### PR DESCRIPTION
**Pull request by mikeblas**
targets .Net Core 3.1

### CODE REVIEW

**Comment by decriptor** [comment]
Do you want to rebase this now that your other PR#191 is merged?

Also, I wonder if we should add other targets here. In particular, netstandard2.1? Would that be better than .net core 3.1?

**Comment by mikeblas** [comment]
That makes sense -- I've rebased and pushed, so I think this PR is updated.

I can't say what other targets are necessary. For me, .Net Core is really helpful so I can use this lib when processing files files on a server to transcode or catalog on a server.  Maybe it's a good idea to bump to 4.8 for .NET and 2.2 (right?) for Standard.  But since I'm not 100% positive of it, I didn't do it.

**Comment by decriptor** [comment]
I'll think about this tonight and add accordingly. Thanks for the PR

**Comment by mikeblas** [comment]
Great -- I'm sure you'll make the right call. I hope we can add .Net Core support soon, though.

**Comment by willkara** [comment]
Just found this issue from Google. Seems like NuGet still complains on .NET Core 3.1 installs.

Severity	Code	Description	Project	File	Line	Suppression State

Warning	NU1701	Package 'taglib 2.1.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETCoreApp,Version=v3.1'. 

This package may not be fully compatible with your project.	

MeMa	C:\Users\wkara\source\repos\MeMa\MeMa\MeMa.csproj	1

**Comment by decriptor** [comment]
My apologies on this. Lets see if I can finally knock this out this weekend.

**Comment by decriptor** [comment]
@willkara just a quick follow up. I'm working on this right now, but looking at your error output I think you might be using an older version. Can you make sure you are pulling this nuget: https://www.nuget.org/packages/TagLibSharp/

**Comment by willkara** [comment]
Just re-downloaded in NuGet v2.2.0.

 

Was able to do a simple load like this, no problem:

 

var file = TagLib.File.Create(<””>);

 

Maybe an old version was cached/used somehow.

 

I’ll test again once the new NuGet version is pushed up.

 

*	Will

**Comment by decriptor** [comment]
Closing in favor of #215

**Pull request closed without merging**
